### ISSUE TITLE
I want to extract all the html information.

### ISSUE THREAD

**Issue by haolin96** [Norconex/crawlers#950]
Hello,

I would like to extract all the html elements from the websites to store. But I can only get the text content inside them in content field. I can't find where the elements such as </body> <a src = /> has been deleted. Can you please help me achieve my goal?

**Comment by ohtwadi** [comment]
One approach is to copy the HTML to a field before the HTML gets parsed (i.e. as a pre-parse handler). Something like this could do it (not tested):

```xml
  <tagger class="com.norconex.importer.handler.tagger.impl.TextPatternTagger">
      <restrictTo field="document.contentType">text/html</restrictTo>
      <pattern field="doc_html">.*</pattern>
  </tagger>
```

**Comment by hadupa** [comment]
I am also curious, so I will bump this. Tested the above suggested approach but it did not work due to several errors caused by deprecations. Currently trying to implement a similar solution using the RegexTagger.  

https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/tagger/impl/RegexTagger.html

**Comment by ohtwadi** [comment]
Perhaps the [DOMPreserveTransformer](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/transformer/impl/DOMPreserveTransformer.html) will be helpful.
